# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Sunny Mishra"

# A description of your site for meta tag, search engine results.
description: "A minimal & modern blog covering the Life and Journey 
of a Software Developer. Learn Product based software company interview strategies and 
an anecdote or two from these experiences."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: #"/blog"

# The base hostname & protocol of your site for where absolute urls are needed.
url: "http://www.sunnymishra.com"

linkedin_profile_url: https://www.linkedin.com/in/sunny-mishra

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "UA-162755346-1"

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Tags
    url: /tags
#  - text: Style Guide
#    url: /style-guide/

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false